imports
imports
	^ {(#'NetworkProtocols' -> #(#SMTPClient #SMTPClient)).
	(#'GraphicsDisplay Objects' -> #(#Form)).
	(#Colors -> #(#Color)).
	(#'Collections-Strings' -> #(#String)).
	(#Transcript -> #(#Transcript)).
	(#'CollectionsUnordered' -> #(#Dictionary)).
	(#UIManager -> #(#UIManager)).
	(#'CollectionsSequenceable' -> #(#OrderedCollection #Array)).
	(#'MorphicWidgetsWindows' -> #(#SystemWindow)).
	(#'SystemSupport' -> #(#Smalltalk)).
	(#'MorphicWidgets-Basic' -> #(#PluggableButtonMorph)).
	(#Kernel
		-> #(#Integer #Date #DateAndTime #Object #Time #Duration #Character)).
	(#'CollectionsSupport' -> #(#CharacterSet)).
	(#'NetworkMIME'
		->
			#(#QuotedPrintableMimeConverter #MIMEDocument #Base64MimeConverter #MIMEHeaderValue)).
	(#'SystemModel' -> #(#Model)).
	(#Rubric -> #(#RubScrolledTextModel)).
	(#'TextCore' -> #(#TextAttribute #Text)).
	(#'MorphicBase' -> #(#AlignmentMorph)).
	(#'CollectionsStreams' -> #(#LimitingLineStreamWrapper #Stream)).
	(#Metalo -> #(#MLModule)).
	(#'MorphicCore' -> #(#World))}