SystemOrganization addCategory: #Metalo!
SystemOrganization addCategory: #'Metalo-Compilation'!
SystemOrganization addCategory: #'Metalo-Core'!
SystemOrganization addCategory: #'Metalo-Documentation'!
SystemOrganization addCategory: #'Metalo-Examples'!
SystemOrganization addCategory: #'Metalo-Integration'!
SystemOrganization addCategory: #'Metalo-IntegrationTests'!
SystemOrganization addCategory: #'Metalo-UnitTests'!
