imports
imports
	^ {(#Metalo
		-> #(#MLModuleExample #MLModule #MLModuleCompilerScope #MLModule)).
	(#Kernel -> #(#Point #Error #Object #AsciiCharset)).
	(#Slot -> #(#WorkspaceVariable)).
	(#'Spec-Core' -> #(#ComposablePresenter)).
	(#'SUnit-Core' -> #(#TestCase)).
	(#'Spec-Layout' -> #(#SpecLayout)).
	(#'Collections-Unordered' -> #(#Dictionary)).
	(#'Spec-Deprecated' -> #(#TextModel)).
	(#'System-Support' -> #(#Smalltalk))}